### ISSUE TITLE
Improved process workflow

### ISSUE THREAD

**Issue by michaelkvance** [google/orbit#10]
Currently it is possible to flush all loaded symbols for the current session by selecting a new process in the process listing. Instead we suggest a workflow where each session is locked to a process once a selection is confirmed. This will also allow things such as auto-loading PDBs, recording/serializing data related to that process into the session, such as PDB references, exe/PDB hash agreements, etc.

**Comment by dimitry-** [comment]
this was resolved, the list of symbols no longer clears when user switches the process.
