### ISSUE TITLE
Bootstrap/build fails on latest Ubuntu with GCC 10 alternative

### ISSUE THREAD

**Issue by pwnorbitals** [google/orbit#1105]
Error : `ERROR: Error reading 'default_relwithdebinfo' profile: Profile not found: gcc10_relwithdebinfo` 
EDIT : Workaround by calling directly `./build.sh gcc9_relwithdebinfo ggp_relwithdebinfo`
EDIT2 : Test Utils.GetCpuUtilization fails (`Unable to determine cpu utilization, wrong format from top command.`) and test script hangs at the end

**Comment by pwnorbitals** [comment]
Thanks a lot, awesome work

**Comment by beckerhe** [comment]
> Thanks a lot, awesome work

Hi Chris,
I just realized I missed to answer here. But apparently compiling with GCC-10 works now for you?

Cheers,
Henning

**Comment by pwnorbitals** [comment]
Yes, looks great, thanks
