### ISSUE TITLE
Support loading of PDB data from a symbol store/server

### ISSUE THREAD

**Issue by michaelkvance** [google/orbit#12]
Currently you must manually select a PDB file to load per process module. It would be useful if you could instead point out a symbol store directly containing multiple PDB files and have Orbit locate the appropriate one for the module. Later, with automatic symbol load support, this could also operate via symbol stores, servers.

**Comment by florian-kuebler** [comment]
@antonrohr, @beckerhe is this what happens on Linux now?

**Comment by dimitry-** [comment]
This is fixed, you can specify search path for symbols to load. Orbit also searches symbols on the service side if they are not found on local machine.
