### ISSUE TITLE
GGP_SDK?

### ISSUE THREAD

**Issue by tpet93** [google/orbit#1232]
Hi I am trying to profile an program on a linux server remotely.

It seems with the ggp version remote debugging over ssh is possible?
However I am missing GGP_SDK and am getting zero results on what it is or where to get it.

**Comment by ronaldfw** [comment]
Hi @tpet93!

GGP_SDK is the SDK required to develop games on Stadia (and not publicly available). Orbit is currently only targeting Stadia as its platform. We have plans to support Linux in general (and also Windows) at some point in the future, but we don't know yet when these versions are available. 

However, with some work, you should be able to get it to work remotely on a Linux server. 

1) Take a look at run_service_ssh.sh (or run_service_ssh.ps on Windows) how the ssh connection with port forwarding is established (it should be enough to adapt the last two lines to your needs). 
2) Run OrbitService on the Linux system you want to profile.
3) Run the UI (either on Linux on Windows) with the --local flag (as we are using port forwarding). 

Mentioning @antonrohr, who can help in case I missed something or if there are more questions. 

Let us know if you run into issues!

**Comment by tpet93** [comment]
Thanks
