### ISSUE TITLE
Build fails on Ubuntu 18 - gcc8

### ISSUE THREAD

**Issue by pfeatherstone** [google/orbit#1295]
I get the following error:
```
ERROR: conanfile.py (OrbitProfiler/None): Error in build() method, line 164
	cmake.build()
	ConanException: Error 2 while executing cmake --build '/home/pf/Downloads/repos/orbit/build_default_relwithdebinfo' '--' '-j12'
```

**Comment by pfeatherstone** [comment]
```
/home/pf/Downloads/repos/orbit/OrbitService/Utils.cpp:188:15: error: ‘transform_reduce’ is not a member of ‘std’
   return std::transform_reduce(begin(proc), end(proc), std::vector<pid_t>{},
```

**Comment by pfeatherstone** [comment]
I think CMakeLists.txt needs to explicitly set C++17 in CFLAGS somewhere

**Comment by pfeatherstone** [comment]
Don't understand, CMakeLists.txt sets c++17 as the minimum standard.

**Comment by pfeatherstone** [comment]
But OrbitService's CMakeLists.txt file doesn't

**Comment by pfeatherstone** [comment]
What was the last release that built on Ubuntu 18  with either gcc or clang?

**Comment by rodolfocangiotti** [comment]
Hey everybody,
I am facing the same issue while trying to build the code on Debian 10. If it could be useful, the issue persists using the default Conan profile both with `compiler.libcxx=libstdc++` and `compiler.libcxx=libstdc++11`.

**Comment by beckerhe** [comment]
Hello everybody,
thanks for reporting this and sorry for the delay.

I hope this is fixed now.

Cheers,
Henning
