### ISSUE TITLE
Orbit installation hangs on test #12

### ISSUE THREAD

**Issue by jhdcs** [google/orbit#1327]
I am trying to install the latest version of Orbit on VirtualBox VM running Ubuntu 20.04. I believe I have all the required dependencies, as the build process seems to run just fine. However, during testing, the `bootstrap_orbit.sh` script gets to test 12 (OrbitQt), and then just hangs. Even after 2 hours, nothing has happened.

Are there logs saved anywhere that can show what's going on internally? I'm not sure what information I can provide to help you debug... All it says is `Start 12: OrbitQT`, and then nothing.

**Comment by florian-kuebler** [comment]
Hi, thanks for reaching out.

We are aware of that issue, and are working on a fix of that. However, it should not effect your actual build or your experience with Orbit.
At that point in time, the complete build should be done already and you should find the binaries under `build_default_relwithdebinfo/bin/Orbit` (or OrbitService respectively).
So you should be able to use those.

Feel free to reach out again, if you have any questions.

(For internal reference, we track this issue as http://b/167365568)

**Comment by illwieckz** [comment]
I got similar issue but on test `#11`:

```
      Start  1: OrbitLinuxTracing
      Start  2: OrbitService
      Start  3: ElfUtils
      Start  4: OrbitBase
      Start  5: OrbitClientData
      Start  6: OrbitClientModel
      Start  7: OrbitCore
      Start  8: OrbitFramePointerValidator
 1/12 Test  #1: OrbitLinuxTracing ................   Passed    0.43 sec
      Start  9: OrbitGl
 2/12 Test  #4: OrbitBase ........................   Passed    0.30 sec
      Start 10: OrbitGgp
 3/12 Test  #5: OrbitClientData ..................   Passed    0.31 sec
      Start 11: OrbitSsh
 4/12 Test  #6: OrbitClientModel .................   Passed    0.30 sec
      Start 12: OrbitQt
 5/12 Test  #9: OrbitGl ..........................   Passed    0.12 sec
 6/12 Test #10: OrbitGgp .........................   Passed    0.12 sec
 7/12 Test #11: OrbitSsh .........................   Passed    0.06 sec
 8/12 Test  #7: OrbitCore ........................   Passed    0.45 sec
 9/12 Test  #8: OrbitFramePointerValidator .......   Passed    0.36 sec
10/12 Test  #3: ElfUtils .........................   Passed    0.67 sec
11/12 Test  #2: OrbitService .....................   Passed    1.15 sec
```

This is stuck since hours now.

**Comment by florian-kuebler** [comment]
Hi and thanks for reporting.
From the log, I would also say that this is `#12 OrbitQt`. `#11` finishes within 0.06 sec.

Anyways. We will continue looking into this. For now, (as said above) at that point in time, all binaries should be successfully build and useable in the `build_default_...` directory.

**Comment by ronaldfw** [comment]
Should we have a build / bootstrap script that builds without testing? And possibly additional scripts for tests and one for combining both?

**Comment by florian-kuebler** [comment]
Hmm good question. Lets loop in  @beckerhe. 
Personally, I'd rather have no test in a deadlock. Especially as executing the tests, is fast (if it does not hang...).

**Comment by beckerhe** [comment]
Yes, good question. Like Florian, I also think we should execute the tests as long as they don't prolong the build time considerably. When our test suite grows and gets longer and longer to execute we probably want to decouple those two steps.

I'd suggest we start with setting reasonable timeouts for our tests. I'm not sure what's the default timeout value. It might be that currently there is no timeout at all.

And of course, we should fix the deadlock.

**Comment by ronaldfw** [comment]
> Personally, I'd rather have no test in a deadlock

Hmm, sure :) We should of course fix that. But my suggestion was rather to make it easy for users to just build Orbit in case there are issues with tests again some time in the future. 

But timeouts sound good. 

I would still suggest that we have a clear message at the end of the script that, in case of timeout or test failure, says something like: "Orbit was built successfully, but some tests failed."

**Comment by beckerhe** [comment]
Alright. I will take care of the timeout and the message.

**Comment by illwieckz** [comment]
> I would still suggest that we have a clear message at the end of the script that, in case of timeout or test failure, says something like: "Orbit was built successfully, but some tests failed."

Yeah, that would be good, it still makes possible for users like me to discover and report bugs while not being blocking. I would not be against an explicit message telling me someting _wrong_ happened and that even if things returned and everything is built as expected, it's not a bad idea to report it.
