### ISSUE TITLE
Document `.orbit` format / add the option to import `drcov` or similar formats

### ISSUE THREAD

**Issue by guye1296** [google/orbit#1608]
Hey!

I understand that Orbit is under heavy development at the moment so there is a lack of documentation.

The `.orbit` format is not documented at all. 
It would be very nice to use the Orbit client / GUI with a trace that was recorded on embedded platforms / generated on different software than Orbit - which would require documentation of the `.orbit` format or an option to import tracing formats such as `drcov` to Orbit.

Thank you!

**Comment by ronaldfw** [comment]
Hey @guye1296, we are aware this is missing right now! Note that we are currently re-working the capture format and there will be a major update to that in the next few weeks. We'll provide documentation for the format once that is stable. 

We are also planning to have a series of Jupyter notebooks that outline how to read data and how to interpret the data together with some visualizations. You can find the first such notebook here: https://github.com/google/orbit/tree/main/contrib/jupyter
Part of this is a Python package `orbitutils` that provides utility functions for reading the capture format: https://github.com/google/orbit/tree/main/contrib/jupyter/orbitutils
(But note that while we already have a start for the Python code, this will need to be modified once the new capture format lands.)

**Comment by florian-kuebler** [comment]
As far as I can see, https://github.com/google/orbit/blob/main/src/CaptureFile/FORMAT.md covers the format. I am closing this for now. Please feel free to reopen.
