### ISSUE TITLE
OrbitApiTest.cpp triggres Werror=stringop-truncation

### ISSUE THREAD

**Issue by AchmadFathoni** [google/orbit#1624]
```
[ 32%] Building CXX object OrbitLinuxTracing/CMakeFiles/OrbitLinuxTracing.dir/ContextSwitchManager.cpp.o
In file included from /usr/include/string.h:519,
                 from /home/toni/.conan/data/gtest/1.10.0/_/_/package/ff3605ff2f853c7007f04e06ee5985ba114b4876/include/gtest/internal/gtest-port.h:250,
                 from /home/toni/.conan/data/gtest/1.10.0/_/_/package/ff3605ff2f853c7007f04e06ee5985ba114b4876/include/gtest/internal/gtest-internal.h:40,
                 from /home/toni/.conan/data/gtest/1.10.0/_/_/package/ff3605ff2f853c7007f04e06ee5985ba114b4876/include/gtest/gtest.h:62,
                 from /home/toni/Documents/source/orbit/OrbitBase/OrbitApiTest.cpp:5:
In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘orbit_api::EncodedEvent::EncodedEvent(orbit_api::EventType, const char*, uint64_t, orbit::Color)’ at /home/toni/Documents/source/orbit/OrbitBase/include/OrbitBase/../../../Orbit.h:309:19,
    inlined from ‘virtual void OrbitApi_Encoding_Test::TestBody()’ at /home/toni/Documents/source/orbit/OrbitBase/OrbitApiTest.cpp:21:85:
/usr/include/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output truncated copying 33 bytes from a string of length 43 [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [OrbitBase/CMakeFiles/OrbitBaseTests.dir/build.make:89: OrbitBase/CMakeFiles/OrbitBaseTests.dir/OrbitApiTest.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

building commit 0183d7b9 with gcc10_release profile

**Comment by dimitry-** [comment]
and in gcc9 we have this after applying #2085 (maybe the right way here to disable this warning for gcc10?):

In function ‘char* strncpy(char*, const char*, size_t)’,
    inlined from ‘orbit_api::EncodedEvent::EncodedEvent(orbit_api::EventType, const char*, uint64_t, orbit::Color)’ at /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/../../../Orbit.h:309:19,
    inlined from ‘orbit_base::TracingScope::TracingScope(orbit_api::EventType, const char*, uint64_t, orbit::Color)’ at /mnt/github/orbitprofiler/src/OrbitBase/Tracing.cpp:33:44:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:34: error: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ specified bound 34 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by dimitry-** [comment]
I have rebuilt main using gcc10 and I do not see this error. Please reopen the bug if you encounter it again.
