### ISSUE TITLE
Do you _really_ need to build your own copy of LLVM?

### ISSUE THREAD

**Issue by gtjoseph** [google/orbit#1746]
After building Orbit for 20 minutes, it finally bombed out with a "no space left on device" error.  A quick look in the ~/.conan directorr revealed a whopping *58GB* of built artifacts in the data/llvm directory.   Fine.  I moved the .conan directory off to another device and symlinked ~/.conan to it and restarted the build.  What did it do???  It blew away the 58G of build products it already created and started from scratch.

Is there some reason you really need to build your own copy of llvm instead of using the system-installed version?

EDIT:  I just checked my conan directory after a successful build.  It contains 82GB of dependency build products.

**Comment by knedlsepp** [comment]
I'd also favor if conan could be removed as a *hard* requirement for building orbit. It's nice to have that convience to build all required dependencies if they cannot provided in any other means but this makes live harder for distro maintainers. 
(I'd like to package this for [NixOS](https://github.com/NixOS/nixpkgs/issues/94555), which provides LLVM, Qt5, etc just fine and doesn't need the orbit build system to build its custom version)

**Comment by bnalkj** [comment]
The build system of orbit is funny

**Comment by vfjerlkj** [comment]
Of course. This can waste your disk. So you need to buy more hard disk and they can earn more money

**Comment by florian-kuebler** [comment]
With https://github.com/google/orbit/pull/4309, we now depend on the system's llvm.
