### ISSUE TITLE
Function hooks can cause broken sampled callstacks

### ISSUE THREAD

**Issue by michaelkvance** [google/orbit#20]
Sometimes hooked functions will cause callstacks to stop having valid full backtraces. See attached file for an example.

<img width="941" alt="orbit-truncated-callstack-from-trampoline" src="https://user-images.githubusercontent.com/15371127/32121964-c5f3da0e-bb2c-11e7-846a-c240d43f95d2.png">

**Comment by dimitry-** [comment]
hooking was reworked completely - I believe this was fixed.
