### ISSUE TITLE
Orbit should interrogate threads for names and display them

### ISSUE THREAD

**Issue by michaelkvance** [google/orbit#21]
Currently Orbit displays thread ids, but many applications use RaiseException or SetThreadDescription mechanisms to set human-readable thread names, which Orbit should attempt to scrape and display.

**Comment by KorkyPlunger** [comment]
The SetThreadDescription API is the new official way to set thread names, so it would be great if that mechanism was supported as well:  https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/17608120-properly-support-native-thread-naming-via-the-sett

**Comment by robbiesri** [comment]
Just chiming in here! This would still be a very useful feature!

**Comment by randomascii** [comment]
GetThreadDescription will retrieve the thread names set with SetThreadDescription and works really well. Chrome, for example, names almost all of its threads and I have found this quite convenient.

If you do add support for grabbing thread names in OrbitProfiler then let me know and I'll update my blog post:
https://randomascii.wordpress.com/2015/10/26/thread-naming-in-windows-time-for-something-better/

**Comment by pierricgimmig** [comment]
GetThreadDescription and SetThreadDescription are actually already on master (https://github.com/pierricgimmig/orbitprofiler/blob/master/OrbitCore/Threading.h).  I really need to release new binaries that include the latest changes... I'll try to do that in the coming week(s).

Btw, @randomascii , it's an honor :-)

On Linux, I think this will be fairly easy to implement... It should be done shortly.

**Comment by randomascii** [comment]
Oh excellent! I updated my blog post to mention this. And now you know that if you want to test thread name support that Chrome is an excellent (if potentially challenging due to its size) target.

**Comment by pierricgimmig** [comment]
Thank you so much @randomascii !!  I really appreciate the mention!  Let's get those binaries out ASAP now :-)

Chrome will indeed be a great test case for Orbit, I'll definitely try it out.

**Comment by florian-kuebler** [comment]
@dpallotti, this should be fixed now. Could you close it?
