### ISSUE TITLE
Failed to run bootsrap shell script.

### ISSUE THREAD

**Issue by navinreddy23** [google/orbit#2332]
![image](https://user-images.githubusercontent.com/71843600/118531134-cc1cd480-b745-11eb-9462-683284cee38d.png)

Hi!

I have all the tools installed. Yet, it fails to link and build.
Any idea what could be missing?

Best regards,
Navin

**Comment by beckerhe** [comment]
Hi Navin,
your log shows `ld terminated with signal 9 [Killed]`. You probably ran out of RAM on your machine. Is that possible?

If that's true you can try to build without debug information. That should need fewer RAM:

```
./build.sh default_release
```

**Comment by navinreddy23** [comment]
Hi @beckerhe,

I have 16GB of RAM and 10GB of swap space. Is it not sufficient?

**Comment by navinreddy23** [comment]
Thanks @beckerhe! It built successfully with the command you have mentioned above.

**Comment by beckerhe** [comment]
Hi Navin,
glad to hear that. For the sake of completeness: 16GB should be enough. Not sure what went wrong.

I'm closing this since it's fixed / worked around.

Cheers,
Henning
