### ISSUE TITLE
Open PDB has non-intuitive behavior

### ISSUE THREAD

**Issue by michaelkvance** [google/orbit#24]
If you use 'Open PDB' from the File menu to try to, say, load a PDB for kernel32.pdb, it seems to override all Module listings in the sampling view, for instance. If you re-select the process and then re-load the PDB through the Modules window, it seems to fix that. Find PDB from modules for kernel32.dll doesn't seem to cause this same issue. It seems Open PDB is a legacy static analysis entry-point, and can create confusion with the more typical process based workflow.

**Comment by dimitry-** [comment]
This is outdated - Open PDB was replaced by Load Symbols functionality.
