### ISSUE TITLE
ERROR: Error reading 'default_relwithdebinfo' profile: Profile not found: gcc9_relwithdebinfo

### ISSUE THREAD

**Issue by Colibrow** [google/orbit#2522]
On Ubuntu 20.04 lts gcc9.0 clang10.0 and run the build.sh

**Comment by beckerhe** [comment]
Can you share the whole output of `./build.sh`? Have you also called `./bootstrap-orbit.sh`?

If you haven't called `./boostrap-orbit.sh` and preferred not to do so you at least have to install the conan configuration: `./third_party/conan/configs/install.sh`.

Let me know if that helps!

--
Henning

**Comment by Colibrow** [comment]
Sorry that I didn't called **bootstrap-orbit.sh** and it works now!

**Comment by beckerhe** [comment]
Great. So I will close this!
