### ISSUE TITLE
Problem building Orbit on Ubuntu 20.04

### ISSUE THREAD

**Issue by NoumanNawaz51** [google/orbit#2565]
make: *** [Makefile:152: all] Error 2
llvm/9.0.1-3@orbitdeps/stable: 
llvm/9.0.1-3@orbitdeps/stable: ERROR: Package '619680d3037b3a3a69b0d120b4f735d8e5810545' build failed
llvm/9.0.1-3@orbitdeps/stable: WARN: Build folder /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545
ERROR: 
	ConanException: Error 2 while executing cmake --build '/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545' '--' '-j8'

After trying again and again and uninstalling and installing clang qt gcc I cannot get past this. Please let me know if anyone has any leads

**Comment by beckerhe** [comment]
Hi,
the actual error should be above the lines you just posted. Can you share some more lines?

--
Henning

**Comment by NoumanNawaz51** [comment]
Here they are,

/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/bugpoint/ToolRunner.cpp:495:21: note: remove ‘std::move’ call
Scanning dependencies of target llvm-dwp
[ 98%] Linking CXX executable ../../bin/lli
[ 98%] Building CXX object tools/dsymutil/CMakeFiles/dsymutil.dir/DwarfStreamer.cpp.o
[ 98%] Building CXX object tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/llvm-dwp.cpp.o
In file included from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMapInfo.h:16,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:16,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueMap.h:28,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/bugpoint/BugDriver.h:18,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/bugpoint/bugpoint.cpp:15:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/ArrayRef.h: In instantiation of ‘llvm::ArrayRef<T>::ArrayRef(const std::initializer_list<_Tp>&) [with T = const llvm::SCEV*]’:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/Analysis/ScalarEvolutionExpressions.h:266:64:   required from here
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/ArrayRef.h:101:37: warning: initializing ‘llvm::ArrayRef<const llvm::SCEV*>::Data’ from ‘std::initializer_list<const llvm::SCEV*>::begin’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
  101 |     : Data(Vec.begin() == Vec.end() ? (T*)nullptr : Vec.begin()),
In file included from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueMap.h:28,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/bugpoint/BugDriver.h:18,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/bugpoint/bugpoint.cpp:15:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h: In instantiation of ‘void llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::initEmpty() [with DerivedT = llvm::DenseMap<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>; KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:791:7:   required from ‘void llvm::DenseMap<KeyT, ValueT, KeyInfoT, BucketT>::init(unsigned int) [with KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:726:52:   required from ‘llvm::DenseMap<KeyT, ValueT, KeyInfoT, BucketT>::DenseMap(unsigned int) [with KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/Analysis/MemoryDependenceAnalysis.h:369:48:   required from here
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:377:7: warning: implicitly-declared ‘constexpr llvm::AssertingVH<const llvm::Value>::AssertingVH(const llvm::AssertingVH<const llvm::Value>&)’ is deprecated [-Wdeprecated-copy]
  377 |       ::new (&B->getFirst()) KeyT(EmptyKey);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueMap.h:33,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/bugpoint/BugDriver.h:18,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/bugpoint/bugpoint.cpp:15:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueHandle.h:277:12: note: because ‘llvm::AssertingVH<const llvm::Value>’ has user-provided ‘ValueTy* llvm::AssertingVH<ValueTy>::operator=(const llvm::AssertingVH<ValueTy>&) [with ValueTy = const llvm::Value]’
  277 |   ValueTy *operator=(const AssertingVH<ValueTy> &RHS) {
      |            ^~~~~~~~
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueHandle.h: In instantiation of ‘static llvm::AssertingVH<T> llvm::DenseMapInfo<llvm::AssertingVH<ValueTy> >::getEmptyKey() [with T = const llvm::Value]’:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:452:33:   required from ‘static const KeyT llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::getEmptyKey() [with DerivedT = llvm::DenseMap<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>; KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:360:38:   required from ‘void llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::destroyAll() [with DerivedT = llvm::DenseMap<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>; KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:750:5:   required from ‘llvm::DenseMap<KeyT, ValueT, KeyInfoT, BucketT>::~DenseMap() [with KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/Analysis/MemoryDependenceAnalysis.h:369:48:   required from here
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueHandle.h:292:12: warning: implicitly-declared ‘constexpr llvm::AssertingVH<const llvm::Value>::AssertingVH(const llvm::AssertingVH<const llvm::Value>&)’ is deprecated [-Wdeprecated-copy]
  292 |     return Res;
      |            ^~~
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueHandle.h:277:12: note: because ‘llvm::AssertingVH<const llvm::Value>’ has user-provided ‘ValueTy* llvm::AssertingVH<ValueTy>::operator=(const llvm::AssertingVH<ValueTy>&) [with ValueTy = const llvm::Value]’
  277 |   ValueTy *operator=(const AssertingVH<ValueTy> &RHS) {
      |            ^~~~~~~~
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueHandle.h: In instantiation of ‘static llvm::AssertingVH<T> llvm::DenseMapInfo<llvm::AssertingVH<ValueTy> >::getTombstoneKey() [with T = const llvm::Value]’:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:456:37:   required from ‘static const KeyT llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::getTombstoneKey() [with DerivedT = llvm::DenseMap<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>; KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:360:72:   required from ‘void llvm::DenseMapBase<DerivedT, KeyT, ValueT, KeyInfoT, BucketT>::destroyAll() [with DerivedT = llvm::DenseMap<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>; KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/DenseMap.h:750:5:   required from ‘llvm::DenseMap<KeyT, ValueT, KeyInfoT, BucketT>::~DenseMap() [with KeyT = llvm::AssertingVH<const llvm::Value>; ValueT = llvm::NonLocalDepResult; KeyInfoT = llvm::DenseMapInfo<llvm::AssertingVH<const llvm::Value> >; BucketT = llvm::detail::DenseMapPair<llvm::AssertingVH<const llvm::Value>, llvm::NonLocalDepResult>]’
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/Analysis/MemoryDependenceAnalysis.h:369:48:   required from here
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueHandle.h:298:12: warning: implicitly-declared ‘constexpr llvm::AssertingVH<const llvm::Value>::AssertingVH(const llvm::AssertingVH<const llvm::Value>&)’ is deprecated [-Wdeprecated-copy]
  298 |     return Res;
      |            ^~~
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/IR/ValueHandle.h:277:12: note: because ‘llvm::AssertingVH<const llvm::Value>’ has user-provided ‘ValueTy* llvm::AssertingVH<ValueTy>::operator=(const llvm::AssertingVH<ValueTy>&) [with ValueTy = const llvm::Value]’
  277 |   ValueTy *operator=(const AssertingVH<ValueTy> &RHS) {
      |            ^~~~~~~~
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/llvm-dwp/llvm-dwp.cpp: In function ‘llvm::Expected<llvm::SmallVector<std::__cxx11::basic_string<char>, 16> > getDWOFilenames(llvm::StringRef)’:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/llvm-dwp/llvm-dwp.cpp:501:19: warning: redundant move in return statement [-Wredundant-move]
  501 |   return std::move(DWOPaths);
      |          ~~~~~~~~~^~~~~~~~~~
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/llvm-dwp/llvm-dwp.cpp:501:19: note: remove ‘std::move’ call
In file included from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/StringExtras.h:16,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/Support/Error.h:19,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/llvm-dwp/DWPError.h:4,
                 from /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/llvm-dwp/llvm-dwp.cpp:13:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/ArrayRef.h: In instantiation of ‘llvm::ArrayRef<T>::ArrayRef(const std::initializer_list<_Tp>&) [with T = llvm::dwarf::Attribute]’:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/llvm-dwp/llvm-dwp.cpp:488:68:   required from here
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/include/llvm/ADT/ArrayRef.h:101:37: warning: initializing ‘llvm::ArrayRef<llvm::dwarf::Attribute>::Data’ from ‘std::initializer_list<llvm::dwarf::Attribute>::begin’ does not extend the lifetime of the underlying array [-Winit-list-lifetime]
  101 |     : Data(Vec.begin() == Vec.end() ? (T*)nullptr : Vec.begin()),
[ 98%] Linking CXX executable ../../bin/bugpoint
[ 98%] Building CXX object tools/llvm-dwp/CMakeFiles/llvm-dwp.dir/DWPError.cpp.o
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
make[2]: *** [tools/lto/CMakeFiles/LTO.dir/build.make:146: lib/libLTO.so.9] Error 1
make[2]: *** Deleting file 'lib/libLTO.so.9'
make[1]: *** [CMakeFiles/Makefile2:9995: tools/lto/CMakeFiles/LTO.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Building CXX object tools/dsymutil/CMakeFiles/dsymutil.dir/MachODebugMapParser.cpp.o
[ 99%] Linking CXX executable ../../bin/llvm-dwp
[ 99%] Building CXX object tools/dsymutil/CMakeFiles/dsymutil.dir/MachOUtils.cpp.o
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/dsymutil/MachODebugMapParser.cpp: In member function ‘llvm::ErrorOr<std::vector<std::unique_ptr<llvm::dsymutil::DebugMap> > > {anonymous}::MachODebugMapParser::parse()’:
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/dsymutil/MachODebugMapParser.cpp:367:19: warning: redundant move in return statement [-Wredundant-move]
  367 |   return std::move(Results);
      |          ~~~~~~~~~^~~~~~~~~
/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545/llvm-9.0.1.src/tools/dsymutil/MachODebugMapParser.cpp:367:19: note: remove ‘std::move’ call
[ 99%] Building CXX object tools/dsymutil/CMakeFiles/dsymutil.dir/NonRelocatableStringpool.cpp.o
[ 99%] Building CXX object tools/dsymutil/CMakeFiles/dsymutil.dir/SymbolMap.cpp.o
[ 99%] Linking CXX executable ../../bin/dsymutil
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
make[2]: *** [tools/llvm-lto/CMakeFiles/llvm-lto.dir/build.make:133: bin/llvm-lto] Error 1
make[2]: *** Deleting file 'bin/llvm-lto'
make[1]: *** [CMakeFiles/Makefile2:10554: tools/llvm-lto/CMakeFiles/llvm-lto.dir/all] Error 2
[ 99%] Built target llc
[ 99%] Built target llvm-c-test
[ 99%] Built target dsymutil
[ 99%] Built target llvm-dwp
[ 99%] Built target lli
[ 99%] Built target bugpoint
make: *** [Makefile:152: all] Error 2
llvm/9.0.1-3@orbitdeps/stable: 
llvm/9.0.1-3@orbitdeps/stable: ERROR: Package '619680d3037b3a3a69b0d120b4f735d8e5810545' build failed
llvm/9.0.1-3@orbitdeps/stable: WARN: Build folder /root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545
ERROR: 
	ConanException: Error 2 while executing cmake --build '/root/.conan/data/llvm/9.0.1-3/orbitdeps/stable/build/619680d3037b3a3a69b0d120b4f735d8e5810545' '--' '-j8'

**Comment by beckerhe** [comment]
The interesting line is the following: `collect2: fatal error: ld terminated with signal 9 [Killed]`

It seem the linker gets killed - probably because you ran out of memory. You can try a release build which needs less memory: `./build.sh default_release`

**Comment by NoumanNawaz51** [comment]
I don't understand. script described above worked and I managed to get past that sigkill problem but it again failed somewhere else.

ERROR: conanfile.py (OrbitProfiler/None): Error in build() method, line 171
	cmake.configure()
	ConanException: Error 1 while executing cd '/home/nomas/Downloads/orbit-release-1.66/build_default_release' && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE="Release" -DCONAN_IN_LOCAL_CACHE="OFF" -DCONAN_COMPILER="gcc" -DCONAN_COMPILER_VERSION="9" -DCONAN_CXX_FLAGS="-m64" -DCONAN_SHARED_LINKER_FLAGS="-m64" -DCONAN_C_FLAGS="-m64" -DCONAN_LIBCXX="libstdc++11" -DCMAKE_INSTALL_PREFIX="/home/nomas/Downloads/orbit-release-1.66/build_default_release/package" -DCMAKE_INSTALL_BINDIR="bin" -DCMAKE_INSTALL_SBINDIR="bin" -DCMAKE_INSTALL_LIBEXECDIR="bin" -DCMAKE_INSTALL_LIBDIR="lib" -DCMAKE_INSTALL_INCLUDEDIR="include" -DCMAKE_INSTALL_OLDINCLUDEDIR="include" -DCMAKE_INSTALL_DATAROOTDIR="share" -DCONAN_CMAKE_POSITION_INDEPENDENT_CODE="ON" -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY="ON" -DCONAN_EXPORTED="1" -DWITH_GUI="ON" -DWITH_CRASH_HANDLING="ON" -DCRASHDUMP_SERVER="" -Wno-dev '/home/nomas/Downloads/orbit-release-1.66'

**Comment by NoumanNawaz51** [comment]
Well After looking more into this I managed to manually place files where they were needed. Now when I ran cmake --build I got these errors shown in log file.
[Error_log3.txt](https://github.com/google/orbit/files/6826511/Error_log3.txt)

**Comment by NoumanNawaz51** [comment]
it resolved after updating and removing manually installed libraries. 
built with this `./build.sh default_release`

> The interesting line is the following: `collect2: fatal error: ld terminated with signal 9 [Killed]`
> 
> It seem the linker gets killed - probably because you ran out of memory. You can try a release build which needs less memory: `./build.sh default_release`
