### ISSUE TITLE
Capture timeline should display thread names/ids, and color deterministically

### ISSUE THREAD

**Issue by michaelkvance** [google/orbit#26]
Currently the capture timeline doesn't display the thread names or ids (normally shown on the left side regardless of timeline position). Nor does it have deterministic coloring; in most profilers this is either user-configured via some mapping mechanism, or deterministically generated via a hash of the name or id.

**Comment by florian-kuebler** [comment]
PIDs and thread names should be reported by now.
We internally track the deterministic coloring under http://b/168104534.

**Comment by florian-kuebler** [comment]
Closing this as colors are deterministic by thread name by now.
