### ISSUE TITLE
ERROR: Error parsing lockfile '/workspace/orbit/third_party/conan/lockfiles/base.lock': Lockfile revisions: 'True' != Current 

### ISSUE THREAD

**Issue by vfjerlkj** [google/orbit#2604]
gitpod /workspace/orbit $ ./build.sh 
ERROR: Profile not found: default
Found gcc 9
Found clang 13.0
gcc>=5, using the major as version

************************* WARNING: GCC OLD ABI COMPATIBILITY ***********************
 
Conan detected a GCC version > 5 but has adjusted the 'compiler.libcxx' setting to
'libstdc++' for backwards compatibility.
Your compiler is likely using the new CXX11 ABI by default (libstdc++11).

If you want Conan to use the new ABI for the default profile, run:

    $ conan profile update settings.compiler.libcxx=libstdc++11 default

Or edit '/home/gitpod/.conan/profiles/default' and set compiler.libcxx=libstdc++11

************************************************************************************

Profile created with detected settings: /home/gitpod/.conan/profiles/default
ERROR: Error parsing lockfile '/workspace/orbit/third_party/conan/lockfiles/base.lock': Lockfile revisions: 'True' != Current revisions 'False'

**Comment by beckerhe** [comment]
It seems your conan version is too old? Can you post the output of `conan --version`?

Did you call `./boostrap-orbit.sh initially? This should install a working version of conan. Of course you can also do that step manually: `python3 -m pip install --user conan==1.36.0`

**Comment by vfjerlkj** [comment]
> It seems your conan version is too old? Can you post the output of `conan --version`?
> 
> Did you call `./boostrap-orbit.sh initially? This should install a working version of conan. Of course you can also do that step manually: `python3 -m pip install --user conan==1.36.0`

works
