### ISSUE TITLE
Add some basic info to your readme

### ISSUE THREAD

**Issue by aprowe** [google/orbit#2689]
With the fancy logo and screenshot I see it and say "Hey this looks great how can I get it?"
Then the next 10 minutes is me re-reading every word of your readme and it doesn't mention 
- minimum requirements
- how to download it
- how to run it 

I can't even use it, I am on ubuntu 16.04. 
Even a 'Documentation Coming Soon' would be nice so I don't feel like Im going crazy looking for a 'hello world' example. 
PLEASE add 2-3 sentences and it will save thousands of peoples the 10 minutes it takes to learn if the tool is right for them or not. 
This was one of the first results on google for "c++ profiler" (No surprise there)

**Comment by florian-kuebler** [comment]
* Minimum requirements and how to build it is mostly covered in the [DEVELOPMENT.md](https://github.com/google/orbit/blob/main/DEVELOPMENT.md).
* Downloads are currently not available.
* How to run it, just got documented in [DOCUMENTATION.md](https://github.com/google/orbit/blob/main/documentation/DOCUMENTATION.md).

We are going to make an update on the README.md soon, but closing this for now. Feel free to re-open if you disagree.
