### ISSUE TITLE
please provide pre-built binaries

### ISSUE THREAD

**Issue by aerosayan** [google/orbit#2729]
orbit has a _lot_ of third party dependencies, and based on other issues submitted ( #1746 ) it seems like 50-80GB of hard disk space is used up to store build artifacts while building LLVM from source.  Obviously that's going to be a strict red flag for devs that might want to use the profiler. It would be helpful if pre-built binaries were provided for linux and windows.

The readme informs us that there are binaries available, and gives us a link ( https://github.com/google/orbit/releases ) however no binaries are provided.

Thanks

**Comment by florian-kuebler** [comment]
#4397 should fix that. For now we are just building a snapshot of main once a week, so no properly manually tested non "dev" release for now.
