### ISSUE TITLE
Expose more information about context switches

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#28]
ETW provides quite a bit of information about context switches that we can easily expose (NewThreadId, OldThreadId, NewThreadPriority, OldThreadPriority, PreviousCState, OldThreadWaitReason, OldThreadWaitMode, OldThreadState, OldThreadWaitIdealProcessor, NewThreadWaitTime).

**Comment by florian-kuebler** [comment]
Internally tracked under http://b/147648918

**Comment by ronaldfw** [comment]
This is an old issue about the Windows version. Should we rather close it?

**Comment by florian-kuebler** [comment]
Yeah, lets close this. We internally track that for Linux, and if we re-enable windows at one point in time, we will look for feature parity with the linux version anyways.
