### ISSUE TITLE
Error when starting capture

### ISSUE THREAD

**Issue by ptagl** [google/orbit#2804]
I've just downloaded and compiled the latest available release (v1.68).

I was able to complete the run process, even though some tests failed (see [build_log.txt](https://github.com/google/orbit/files/7186600/build_log.txt)).

I then started orbit by running:

```
./run_service.sh
./run.sh
```
 
 Everything works until I start a capture, in which case I get the following error:
 
`There were errors with perf_event_open, in particular with: mmap events, fork and exit events, u(ret)probes, sampling, task:task_newtask and task:task_rename tracepoints, sched:sched_switch and sched:sched_wakeup tracepoints." with severity kSevereWarning added to the capture log`

If I continue regardless the error message, the capture seems not to work and when I stop it the application hangs after showing a small popup window "Finalizing capture - Orbit Profiler [BETA]".

**Comment by ronaldfw** [comment]
Looks like you are not starting the service as root.

Try `sudo ./run_service.sh` for the first step. 

The client, started with `./run.sh`, doesn't have to run as root.

**Comment by ptagl** [comment]
It works, sorry, I didn't notice it in the documentation!

**Comment by ronaldfw** [comment]
Glad that it now works for you, thanks for confirming! 

And thanks for trying out / using Orbit!
