### ISSUE TITLE
Remote profiling

### ISSUE THREAD

**Issue by hrkrx** [google/orbit#2970]
I built orbit inside a docker container, ran the service and tried to connect to it, but it did not work.
I forwarded ports 44765 and 44766 and ran orbit on my Windows machine with the `--local` argument.

Am I missing a step?

**Comment by beckerhe** [comment]
What error message do you get? And could you also paste the contents of the log file in `%APPDATA%\OrbitProfiler\logs`?

**Comment by hrkrx** [comment]
I do not get an error message, I do not have a logs folder, and just nothing happens.

Also this might be relevant: I used the provided windows binaries (unlike on linux where I compiled the latest version)

**Comment by beckerhe** [comment]
Ahh that's a problem. The provided Windows binaries (Version 1.0.2 and below) don't support connecting to a remote service and don't have the local flag. You need to use the same version as the Orbit Service running on your Linux machine.

Unfortunately we don't provide precompiled binaries at this point. I'm afraid you have to compile Orbit also for Windows.

**Comment by hrkrx** [comment]
Thank you for your help!
