### ISSUE TITLE
Failure to compile on Ubuntu 21.04

### ISSUE THREAD

**Issue by benpm** [google/orbit#2997]
```
$ ./bootstrap-orbit.sh
```
does a bunch of stuff [(see log.txt)](https://github.com/google/orbit/files/7491893/log.txt), then fails as following:
```
ERROR: crashpad/20200624@orbitdeps/stable: Error in source() method, line 77
	self.run("gclient sync --no-history")
	ConanException: Error 2 while executing gclient sync --no-history
```
im guessing it might have something to do with qt5-default not being available on 21.04?

**Comment by beckerhe** [comment]
Hi Ben,
that seems to be rather related to some Python2/Python3 issue. Apparently crashpad still needs Python2 to build properly.

From your log:

```
[E2021-11-07T01:27:58.957652-06:00 38987 0 annotate.go:241]   reason: could not find Python for: 2.7.0
```

I suggest to build without crashpad. To do so you have to create a new conan profile file in `~/.conan/profiles/`.

Let's call it `default_no_crashpad` (`~/.conan/profiles/default_no_crashpad`) with the following contents:
```
include(default_relwithdebinfo)

[options]
OrbitProfiler:with_crash_handling=False
```

Then you should be able to build Orbit without crash handling support by calling: `./build.sh default_no_crashpad` in the repo root.

Cheers,
Henning

**Comment by benpm** [comment]
Sure enough, Python 2 did the trick. Thanks!
