### ISSUE TITLE
There were errors with perf_event_open in Docker

### ISSUE THREAD

**Issue by TuMePJlaH** [google/orbit#3011]
I have docker image with ubuntu 20.04.1 (kernel 5.11.0-38-generic).
I downloaded the latest version of the repository. 
Run ./bootstrap-orbit.sh.
Start:
```
sudo ./build_default_relwithdebinfo/bin/OrbitService
./build_default_relwithdebinfo/bin/Orbit --local
```
When I press "Start a capture" I got error:
![image](https://user-images.githubusercontent.com/17141754/141121773-8aa1f94b-b840-438a-9d02-b3ec4b00551f.png)

If I do the same steps on the host (without docker) everything works fine.

**Comment by TuMePJlaH** [comment]
I saw the Issue [#2804](https://github.com/google/orbit/issues/2804), but I started service with sudo and it doesn't help.

**Comment by beckerhe** [comment]
This is probably due to restrictions in the docker container. Have you tried starting your docker container with the `--privileged` option?

**Comment by TuMePJlaH** [comment]
Thanks for the quick response!
Tried it, it doesn't help.

**Comment by beckerhe** [comment]
In that case can you provide the log file that is generated by the service? It should be placed in /var/log/OrbitService.log (in the docker container)

**Comment by TuMePJlaH** [comment]
[OrbitService.log](https://github.com/google/orbit/files/7513180/OrbitService.log)

**Comment by TuMePJlaH** [comment]
I don't know what I did and why the folder is empty by default.
Thanks for your quick help! 
It was "the fastest help in the entire Wild West"!
