### ISSUE TITLE
LLVM does not compile - Illegal instruction

### ISSUE THREAD

**Issue by vilarion** [google/orbit#3033]
Hello,

I am trying to run `./bootstrap-orbit.sh`. While building llvm the following error occurs:
```
[ 10%] Linking CXX static library ../../../lib/libLLVMRemarks.a
[ 10%] Built target LLVMRemarks
[ 10%] Building Attributes.inc...
Illegal instruction
gmake[2]: *** [source/include/llvm/IR/CMakeFiles/intrinsics_gen.dir/build.make:148: source/include/llvm/IR/Attributes
.inc] Fehler 132
gmake[1]: *** [CMakeFiles/Makefile2:4747: source/include/llvm/IR/CMakeFiles/intrinsics_gen.dir/all] Fehler 2
gmake: *** [Makefile:156: all] Fehler 2
llvm-core/12.0.0@orbitdeps/stable:
llvm-core/12.0.0@orbitdeps/stable: ERROR: Package '35eaf942a6bf65314d0b90c76c7918175e1e5e0b' build failed
llvm-core/12.0.0@orbitdeps/stable: WARN: Build folder /home/vilarion/.conan/data/llvm-core/12.0.0/orbitdeps/stable/bu
ild/35eaf942a6bf65314d0b90c76c7918175e1e5e0b
ERROR: llvm-core/12.0.0@orbitdeps/stable: Error in build() method, line 223
        cmake.build()
        ConanException: Error 2 while executing cmake --build '/home/vilarion/.conan/data/llvm-core/12.0.0/orbitdeps/
stable/build/35eaf942a6bf65314d0b90c76c7918175e1e5e0b' '--' '-j1'
```
* Version `bc3043a55`.
* This attempt ran in one thread, I also tried 3 (limited with CONAN_CPU_COUNT).
* The OS is Debian 11.1.
* Tried different compilers: clang9, gcc10 and a clang12 snapshot.
* Tried CMake 3.18.4 and 3.21.4
* Tried to delete my `~/.conan` and build dirs, without any change.
* Interestingly enough, on my local machine, with the same OS, everything builds just fine.

Any ideas would be very much appreciated. :)

**Comment by vilarion** [comment]
Additional error messages in syslog:
* When trying to run OrbitService (copied from my local machine): `kernel: [676111.731338] traps: OrbitService[1977960] trap invalid opcode ip:55a81c969abf sp:7ffef3383fe0 error:0 in OrbitService[55a81bf68000+a41000]`
* When compiling fails: `kernel: [676685.066560] traps: llvm-tblgen[1982740] trap invalid opcode ip:55be258d1661 sp:7ffd7c562980 error:0 in llvm-tblgen[55be256aa000+2b4000]`

Maybe the rather old CPU is not compatible (Intel Core i7 920).

**Comment by beckerhe** [comment]
Hi Andreas,
yes, that's probably related to your CPU not supporting AVX. We currently compile everything with `-march=sandybridge` to ensure AVX support. But that's only needed for some tests. You can remove that flag from the conan profiles in `~/.conan/profiles/linux_common` and it should still work. I'm not sure if some test will refuse to compile or if they will just fail when running. Maybe you have to comment some tests that are AVX-related.

I hope that helps.

Cheers,
Henning

**Comment by vilarion** [comment]
Hi Henning,
indeed, it is compiling now. Thank you so much for your help, I wouldn't have found this in months. Also thank you for a great tool. Ever since I started using orbit a few months ago, profiling C++ applications is actually fun.

Have a great week.

Kind Regards,
Andreas
