### ISSUE TITLE
gRPC does not compile

### ISSUE THREAD

**Issue by vilarion** [google/orbit#3039]
Hello again,

After #3033 got resolved, compilation now dies with grpc. Can this be fixed with some configuration like the last issue, or have I reached the end of the road now? The setup is the same as in #3033. As last time compiling a stand-alone gRPC v1.27.3 works without problems.
```
[ 98%] Linking CXX static library ../lib/libgrpc++.a
[ 98%] Built target grpc++
[ 99%] Running gRPC C++ protocol buffer compiler on src/proto/grpc/status/status.proto
[ 99%] Running gRPC C++ protocol buffer compiler on src/proto/grpc/reflection/v1alpha/reflection.proto
[ 99%] Building CXX object source_subfolder/CMakeFiles/grpc++_alts.dir/src/cpp/common/alts_context.cc.o
--grpc_out: protoc-gen-grpc: Plugin killed by signal 4.
gmake[2]: *** [source_subfolder/CMakeFiles/grpc++_reflection.dir/build.make:75: gens/src/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:507: source_subfolder/CMakeFiles/grpc++_reflection.dir/all] Fehler 2
gmake[1]: *** Es wird auf noch nicht beendete Prozesse gewartet....
[ 99%] Building CXX object source_subfolder/CMakeFiles/grpc++_alts.dir/src/cpp/common/alts_util.cc.o
--grpc_out: protoc-gen-grpc: Plugin killed by signal 4.
gmake[2]: *** [source_subfolder/CMakeFiles/grpc++_error_details.dir/build.make:75: gens/src/proto/grpc/status/status.grpc.pb.cc] Fehler 1
gmake[1]: *** [CMakeFiles/Makefile2:255: source_subfolder/CMakeFiles/grpc++_error_details.dir/all] Fehler 2
[ 99%] Building C object source_subfolder/CMakeFiles/grpc++_alts.dir/src/core/ext/upb-generated/src/proto/grpc/gcp/altscontext.upb.c.o
[ 99%] Building C object source_subfolder/CMakeFiles/grpc++_alts.dir/src/core/ext/upb-generated/src/proto/grpc/gcp/handshaker.upb.c.o
[ 99%] Building C object source_subfolder/CMakeFiles/grpc++_alts.dir/src/core/ext/upb-generated/src/proto/grpc/gcp/transport_security_common.upb.c.o
[ 99%] Linking CXX static library ../lib/libgrpc++_alts.a
[ 99%] Built target grpc++_alts
gmake: *** [Makefile:136: all] Fehler 2
grpc/1.27.3@orbitdeps/stable:
grpc/1.27.3@orbitdeps/stable: ERROR: Package '41cff12fb3e7836eabacd1edd1d96a48b522a579' build failed
grpc/1.27.3@orbitdeps/stable: WARN: Build folder /home/vilarion/.conan/data/grpc/1.27.3/orbitdeps/stable/build/41cff12fb3e7836eabacd1edd1d96a48b522a579
ERROR: grpc/1.27.3@orbitdeps/stable: Error in build() method, line 112
        cmake.build()
        ConanException: Error 2 while executing cmake --build '/home/vilarion/.conan/data/grpc/1.27.3/orbitdeps/stable/build/41cff12fb3e7836eabacd1edd1d96a48b522a579/build_subfolder' '--' '-j3'
```

syslog:
```
kernel: [782162.829169] traps: grpc_cpp_plugin[2277259] trap invalid opcode ip:413919 sp:7ffc73b09b90 error:0 in grpc_cpp_plugin[400000+166000]
kernel: [782162.846781] traps: grpc_cpp_plugin[2277265] trap invalid opcode ip:413919 sp:7fffb8fd5bd0 error:0 in grpc_cpp_plugin[400000+166000]
```

**Comment by beckerhe** [comment]
You probably still have a version of the grpc_codegen conan package on your machine that has been compiled with the wrong compiler flags. I'd start by removing this to see if that helps: `conan remove -p grpc_codegen/1.27.3@orbitdeps/stable`

When building afterwards it should be automatically recompiled - with the correct flags this time.

**Comment by vilarion** [comment]
Thanks, I tried that today, but it seems it was still cached somewhere after that. So I tried this:
* deleted the complete ~/.conan dir
* ran bootstrap with DONT_COMPILE="yes"
* removed all occurrences of `-march=sandybridge` from `linux_common`
* ran `build.sh`

The error remains the same.

**Comment by beckerhe** [comment]
That's kind of expected because the dont-compile flag only affects the build of Orbit itself, the dependencies have probably been compiled during the bootstrap call. I suggest you try the following:

1. Clear the cache: `conan remove -f \*`
2. Remove the `-march=sandybridge` from `linux_common` if you haven't done that yet.
3. Compile Orbit (and the dependencies) using `build.sh` and your preferred profile.

Be aware not to call `bootstrap-orbit.sh` because this will overwrite the `linux_common` profile and add the flag again. After calling it once you should be good using `build.sh` from that point on.

Cheers,
Henning

**Comment by vilarion** [comment]
Thanks! As you can tell, I have never used conan before. After cleaning up the cache this way and disabling `UserSpaceInstrumentation/TrampolineTest` I can now run OrbitService on my server and connect to it via an SSH tunnel.
This absolutely amazing, thank you so much for walking me through this!
