### ISSUE TITLE
build.sh failure

### ISSUE THREAD

**Issue by dantenoguera** [google/orbit#3232]
Hi after executing build.sh I got:

```
ERROR: crashpad/20200624@orbitdeps/stable: Error in source() method, line 77
	self.run("gclient sync --no-history")
	ConanException: Error 2 while executing gclient sync --no-history
```

before that got the warning:

```
Warning: Running gclient on Python 3. 
If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.
```

**Comment by kamilla0503** [comment]
I have the same issue. 

`Error: Command 'download_from_google_storage --no_resume --no_auth --bucket=chromium-clang-format --sha1_file buildtools/linux64/clang-format.sha1' returned non-zero exit status 1 in /home/kamilla/.conan/data/crashpad/20200624/orbitdeps/stable/source
ERROR: crashpad/20200624@orbitdeps/stable: Error in source() method, line 77
	self.run("gclient sync --no-history")
	ConanException: Error 2 while executing gclient sync --no-history
`
Would it be solved?

**Comment by beckerhe** [comment]
I'm not sure what the exact cause for this problem is. But there is a simple workaround. You can just disable crash handling:

```bash
conan profile update options.OrbitProfiler:with_crash_handling=False default_release
```

Afterwards, try to build again:

```bash
./build.sh default_relwithdebinfo
```

**Comment by onurtore** [comment]
> I'm not sure what the exact cause for this problem is. But there is a simple workaround. You can just disable crash handling:
> 
> ```shell
> conan profile update options.OrbitProfiler:with_crash_handling=False default_release
> ```
> 

This outputs: 

ERROR: Profile not found: default_release

**Comment by beckerhe** [comment]
Hi Onur,
you once have to trigger a build for the default_release profile. This will create the profile. If that fails you can disable crash handling. Like so:

```
./build.sh default_release # If that succeeds all good, otherwise continue
conan profile update options.OrbitProfiler:with_crash_handling=False default_release
./build.sh default_release # Second try
```

I hope that helps.

Cheers,
Henning

**Comment by onurtore** [comment]
Hi @beckerhe,
Yes it works, thanks. 

I was running the default bootstrap-orbit.sh, I see some additional lines after ./build.sh in that file, do I need to re-run bootstrap-orbit.sh after this, or is this enough. There are some lines related to PRE_COMMIT_HOOK_FILE.

Also I just wanted to say,  this installation script is awesome. Works like a charm.
