### ISSUE TITLE
How to start Orbit on Linux

### ISSUE THREAD

**Issue by cflaviu** [google/orbit#3388]
I have built Orbit on Linux but launching the Orbit executable the interface appears differently compared to the Windows interface. What should be done to start the application to look like Windows interface?
See Linux UI https://ibb.co/hZFhRcY

**Comment by florian-kuebler** [comment]
You are almost there. For Linux local profiling you need to start the `Orbit` executable with the `--local` option and run our collector service `OrbitService` from another bash (this needs to run as root for most profiling features).

**Comment by HOTFIGHTER** [comment]
can it run on MAC？

**Comment by cflaviu** [comment]
> You are almost there. For Linux local profiling you need to start the `Orbit` executable with the `--local` option and run our collector service `OrbitService` from another bash (this needs to run as root for most profiling features).

Thank you, it worked!

**Comment by cflaviu** [comment]
> can it run on MAC？

Orbit, the Open Runtime Binary Instrumentation Tool, is a standalone C/C++ profiler for Windows and Linux.
