### ISSUE TITLE
is there any working principle about orbit for understanding

### ISSUE THREAD

**Issue by HOTFIGHTER** [google/orbit#3417]

**Comment by florian-kuebler** [comment]
Hi, I am not 100% sure what you are looking for. But have you checked the *Features* and *Workflow* sections in the [readme](https://github.com/google/orbit#readme)?

Hopefully, that helps.

**Comment by florian-kuebler** [comment]
#4272 should add extra info. Closing this for now. Please re-open if there is still anything that is missing.
