### ISSUE TITLE
404 on 'More information on symbol loading' button

### ISSUE THREAD

**Issue by d0wnFvll** [google/orbit#3496]
Hi there!

When I'm trying to load symbols, clicking `Add Symbol Location` and then clicking `More information on symbol loading`

![more_info_on_symbol_loading](https://user-images.githubusercontent.com/102362394/160229026-346dd484-9cc8-44c6-a3f1-d024018a48f0.png)

I get `404 Page Not Found` error 

![404](https://user-images.githubusercontent.com/102362394/160229049-9f1ee7ed-5d37-4bff-b060-db6fe9b0f9cb.png)

And as far as I can see, the code and link are located in `src/ConfigWidgets/SymbolsDialog.cpp` on the line `288`

```
void SymbolsDialog::OnMoreInfoButtonClicked() {
  QString url_as_string{
      "https://developers.google.com/stadia/docs/develop/optimize/"
      "profile-cpu-with-orbit#load_symbols"};
  if (!QDesktopServices::openUrl(QUrl(url_as_string, QUrl::StrictMode))) {
    QMessageBox::critical(this, "Error opening URL",
                          QString("Could not open %1").arg(url_as_string));
  }
}
```

To be honest, I don't know whether this is a bug or I have no permission to reach this page, so I'd be glad if you provide some information about this

**Comment by florian-kuebler** [comment]
Hey, thanks for raising this issue and I am sorry for the inconveniences. As you suspected, it is about permissions.
Orbit, right now, has primary focus on Stadia and is also integrated into Stadia's partner documentation. Thus, all our links refer to those, restricted pages.

We are aware of this issue and plan to have public documentation available, which gets linked to on non Stadia use. However, we can't promise on any timeline for this to happen.

Of course, if you have specific question about symbol loading, feel free to ask that here.

(This issue is tracked internally under http://b/227141253)

**Comment by lo11y** [comment]
> Hey, thanks for raising this issue and I am sorry for the inconveniences. As you suspected, it is about permissions. Orbit, right now, has primary focus on Stadia and is also integrated into Stadia's partner documentation. Thus, all our links refer to those, restricted pages.
> 
> We are aware of this issue and plan to have public documentation available, which gets linked to on non Stadia use. However, we can't promise on any timeline for this to happen.
> 
> Of course, if you have specific question about symbol loading, feel free to ask that here.
> 
> (This issue is tracked internally under http://b/227141253)

Thanks for the answer!

Is there any other way to get more documentation on this project besides `README.md` files?

**Comment by florian-kuebler** [comment]
Unfortunately, `README.md` is alls our public documentation for now. We are planning to extend on that documentation, but as said, can't promise on any timeline.

But as said, if you have questions feel to just ask those.

In particular, based on your original question, it seems that you stumbled over symbol loading:
We are currently working on more automated ways to load symbols, but for now we rely on the user to either specify symbol store directories or symbol/debug files directly. Orbit will automatically find`.debug` files that are named like the executable/shared library, or if the binary file contains the `.symtab` section directly, i.e. is not stripped (@antonrohr  correct me if I am wrong here). However, you still need to click "Load symbols" in the UI.

Having symbol loaded in Orbit, not only to provide better sampling information (without symbols, Orbit is not able to stack samples from the same function together), but most importantly, it will enable you to use dynamic instrumentation, to get precise timestamps from function execution.
