### ISSUE TITLE
Stream pointer might be NULL

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/orbit#357]
'buffer ' is defined here, but may be NULL
https://github.com/google/orbit/blob/de8517fcb68d24da5cc88a6c10e64905df43ebf6/OrbitGl/shader.cpp#L32
Stream pointer might be NULL
https://github.com/google/orbit/blob/de8517fcb68d24da5cc88a6c10e64905df43ebf6/OrbitGl/shader.cpp#L33

**Comment by dimitry-** [comment]
The code in question was removed.
