### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/orbit#367]
Memory is allocated
https://github.com/google/orbit/blob/de8517fcb68d24da5cc88a6c10e64905df43ebf6/OrbitCore/EventUtils.cpp#L402
but at the end of function，never free it
https://github.com/google/orbit/blob/de8517fcb68d24da5cc88a6c10e64905df43ebf6/OrbitCore/EventUtils.cpp#L428

**Comment by layderv** [comment]
Correct me if I'm wrong.

A `pMapInfo` is defined here:

> https://github.com/google/orbit/blob/de8517fcb68d24da5cc88a6c10e64905df43ebf6/OrbitCore/EventUtils.cpp#L171

Then used here, passed as a reference, initially set to `NULL`:

> https://github.com/google/orbit/blob/de8517fcb68d24da5cc88a6c10e64905df43ebf6/OrbitCore/EventUtils.cpp#L214

Then it is used as you say in those lines.
Then it is still used either as `NULL` or wherever `malloc(MapSize)` returned.
Then it is `free()`'d here:

> https://github.com/google/orbit/blob/de8517fcb68d24da5cc88a6c10e64905df43ebf6/OrbitCore/EventUtils.cpp#L278

**Comment by ayaankhan98** [comment]
can i make a PR, to fix this?

**Comment by QiAnXinCodeSafe** [comment]
Of course, if you're sure it's a issue

**Comment by ayaankhan98** [comment]
well i am not sure that it's actually a issue, but it's always good to deallocate resouces after use

**Comment by Mostafa-ashraf19** [comment]
Can use Smart pointers instead of raw pointer !, or I think that's wanted to deallocate at a certain line from 418 to 423 can give me example try it for knowing it's not entry to condition at line 415!
