### ISSUE TITLE
Building on Arch Linux fails

### ISSUE THREAD

**Issue by damiandixon** [google/orbit#3797]
Using gcc & g++ version 11. Note 12 is available.
Linux juno-console 5.15.47-1-lts #1 SMP Tue, 14 Jun 2022 17:59:27 +0000 x86_64 GNU/Linux

Unable to get crashpad to install or build, so disabled.

When building main and 1.80 the following tests fail:
```
The following tests FAILED:
        384 - ExecuteInProcessTest.ExecuteInProcess (Child aborted)
        385 - ExecuteInProcessTest.ExecuteInProcessWithMicrosoftCallingConvention (Child aborted)
        388 - InjectLibraryInTraceeTest.OpenUseAndCloseLibraryInUserCode (Child aborted)
        389 - InjectLibraryInTraceeTest.OpenUseAndCloseLibraryInSyscall (Child aborted)
        394 - InstrumentProcessTest.Instrument (Child aborted)
        396 - InstrumentProcessTest.ExitPayloadDoesNotUseX87Fpu (Child aborted)
        417 - InstrumentFunctionTest.DoSomething (Child aborted)
        418 - InstrumentFunctionTest.CheckStackAlignedTo16Bytes (Child aborted)
        420 - InstrumentFunctionTest.LongEnough (Child aborted)
        421 - InstrumentFunctionTest.RipRelativeAddressing (Child aborted)
        422 - InstrumentFunctionTest.UnconditionalJump8BitOffset (Child aborted)
        423 - InstrumentFunctionTest.UnconditionalJump32BitOffset (Child aborted)
        424 - InstrumentFunctionTest.ConditionalJump8BitOffset (Child aborted)
        425 - InstrumentFunctionTest.ConditionalJump32BitOffset (Child aborted)
        427 - InstrumentFunctionTest.CheckIntParameters (Child aborted)
        428 - InstrumentFunctionTest.CheckFloatParameters (Child aborted)
        429 - InstrumentFunctionTest.CheckM256iParameters (Child aborted)
        430 - InstrumentFunctionTest.CheckIntParametersMsAbi (Child aborted)
        431 - InstrumentFunctionTest.CheckFloatParametersMsAbi (Child aborted)
        432 - InstrumentFunctionTest.CheckNoX87UnderflowInReturnTrampoline (Child aborted)
        437 - InstrumentFunctionTest.LongConditionalJump32BitOffsetBackToBeginning (Child aborted)
        438 - InstrumentFunctionTest.UnableToDisassembleBadInstruction (Child aborted)
```
If I disable tests in the build the build finishes.

Data does appear to be collected though and looks reasonable.

I get around 23% DWARF unwinding errors.

run.sh and run_service.sh are run using sudo.

**Comment by florian-kuebler** [comment]
Some tests are actually flaky, or require to run as root. The build actually finishes even without the tests passing. But I see that you actually managed to run and take a capture.

23% DWARF unwinding errors sound alerting. What is the target that you profile? You can also right-click "Select these callstacks" to the unwinding errors in the Top-Down view, and inspect the "broken" callstacks in the "Sampling (Selection)" tab. Without further details, its pretty hard to tell much more.

In general, DWARF unwinding errors are related to missing or broken DWARF unwind information.

**Comment by florian-kuebler** [comment]
We've recently fixed a bug related with the tests, so might be worth another try.
