### ISSUE TITLE
build.sh fails, Error in build() method

### ISSUE THREAD

**Issue by imadchabounia** [google/orbit#3923]
Hi,

I got the error below while I was trying to run build.sh and thus I wasn't able to build.

<pre>[202/469] CXX obj/third_party/googletest/googletest/googlemock/test/gmock_all_test.gmock-generated-matchers_test.o
ninja: build stopped: subcommand failed.
crashpad/20200624@orbitdeps/stable: 
<font color="#CC0000"><b>crashpad/20200624@orbitdeps/stable: </b></font><font color="#D3D7CF"><b>ERROR: Package &apos;c7f7792208a14227efdf8360c42b28462d7faba0&apos; build failed</b></font>
<font color="#C4A000"><b>crashpad/20200624@orbitdeps/stable: </b></font><font color="#D3D7CF"><b>WARN: Build folder /home/aimad/.conan/data/crashpad/20200624/orbitdeps/stable/build/c7f7792208a14227efdf8360c42b28462d7faba0</b></font>
<font color="#CC0000"><b>ERROR: crashpad/20200624@orbitdeps/stable: Error in build() method, line 164</b></font>
	<font color="#CC0000"><b>self.run(&quot;ninja -j%d -C %s&quot; % (tools.cpu_count(), self._build_name), run_environment=True)</b></font>
	<font color="#CC0000"><b>ConanException: Error 1 while executing ninja -j6 -C out/Conan</b></font></pre>

**Comment by florian-kuebler** [comment]
Hey, sorry for the late response.

You should be able to build by disabling crashpad, as described in [#3232](https://github.com/google/orbit/issues/3232).
