### ISSUE TITLE
Possible Optimization (?)

### ISSUE THREAD

**Issue by Pranav-yadav** [google/orbit#4025]
While reading and understanding the code saw this;
https://github.com/google/orbit/blob/9ae3318b8e175b584e7a7f72a3f7b128356fe830/src/ApiUtils/EncodedString.cpp#L16-L20

what's the logic behind taking 8 different `encoded_chunk`s as a *value* and `encoded_chunk_additional` as a *reference* ?

can we optimize this function (*overall*) by having a single *custom* data structure; `struct` which has all of these *eight* encoded chunk variables initialized to `0`. Or even array of 8 members, keeping `encoded_chunk_additional` and `encoded_chunk_addition_count` as it is (_if dependent functions are made that way_).
And when calling this function passing such struct Or array variable (?)
OR taking a *single reference* (?) (_if it's not the concern_)

Doing so, can we also optimize this code; (The main question) 
https://github.com/google/orbit/blob/9ae3318b8e175b584e7a7f72a3f7b128356fe830/src/ApiUtils/EncodedString.cpp#L23-L53

PS: I'm not completely aware of the codebase just getting started, so please consider this while replying :)

**Comment by florian-kuebler** [comment]
Hey, so the `EncodedString` system is far from being perfect, but the situation is also not as simple.

So very quick background we do have those strangly encoded strings:
We are using protobufs to transmit data from capturing to our client UI. And we send a lot of data, so every bit of performance matters.
Now, some events contain dynamic strings. However, the `string` (or `bytes` or `repeated ...`) types in protobuf yield additional allocations. This is quite a big performance impact. So we can not simply use `string` or `bytes` to send the strings to the client.
Fortunately, protobufs also uses variant size encoding for numbers. So if a 64bit number only needs 16bytes to be represented, then it will not require 64bits. In particular, if the value is 0, we almost have no overhead.
So our idea is to have this special encoding, which for reasonable sized strings (64 characters), our protobuf messages do not require any allocations, while we still allow for arbitrary size strings (hoping that their frequency is low enough to not hit our performance too much).

One thing that you need to keep in mind, is that the encoding/decoding is based on different protos (and not regular c++ classes or structs). So we can not simply have a struct in the proto message to encapsulate the encoded string.
While the actual encode/decode functions (that take the enormous number of arguments) are pretty ugly, they are wrapped by templated functions designed specifically for our protos, making the usage actually better.
You can basically see that the protos have the `encoded_name_1()` or `set_encoded_name_1()` functions, that need to be used at some point.

If you come up with a refactoring that remain (or maybe even improve) the performance, you are more than welcome to create a PR. But as said, please be aware of the situation.

**Comment by Pranav-yadav** [comment]
Thanks for the background and explanation.

Exploring `protobuf`s :)
Will come back to this afterwards..
