### ISSUE TITLE
Can't build with glibc 2.34 because known compile error in abseil

### ISSUE THREAD

**Issue by Flarkk** [google/orbit#4141]
Build will fail on ubuntu 22.04 because the glibc version 2.34 shipped out there generates a compile error when building abseil 20200923.3.
The issue with abseil [is known](https://github.com/abseil/abseil-cpp/issues/952) and has been [fixed since version 20210324.2](https://github.com/abseil/abseil-cpp/pull/967).

I've naively tried to upgrade abseil package from conan but it generates versions mismatch with other dependencies I stopped digging into.

**Comment by Flarkk** [comment]
Note : I was compiling version 1.71 so it may have been fixed since then

**Comment by beckerhe** [comment]
Yes, we have updated Abseil in the mean time. So the problem should be gone when you try to compile from `main` or a recent release version.

I'm closing this bug for now. Feel free to re-open if the problem remains.
