### ISSUE TITLE
BUG: RSA PRIVATE KEY Exposed Publicly which is Sensitive and private

### ISSUE THREAD

**Issue by aravindb26** [google/orbit#4213]
Hi team, Hope u r doing well :)

I have found an issue that RSA PRIVATE KEY was exposed publicly in the following file

```https://github.com/google/orbit/blob/62cf074a8b3b12c479bd8935dc32ca0c2c24d240/external/websocketpp/examples/echo_server_tls/server.pem```

### Proof:
Attached screenshot below
<img width="220" alt="gg__" src="https://user-images.githubusercontent.com/89305482/191019348-ad841b4c-2be5-4ca5-8eed-bb05d395b3ef.png">

**Comment by pierricgimmig** [comment]
As the name of the file suggests, this is an *example* private key of the 'websocketpp' external project. Nothing of concern here.
