### ISSUE TITLE
Userspace Dynamic Instrumentation does not work on Ubuntu 20.04, breaking manual instrumentation

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#4304]
We can revert to uprobes/uretprobes for dynamic instrumentation. However, since manual instrumentation relies on *userspace* dynamic instrumentation, it doesn't work.

**Comment by pierricgimmig** [comment]
Same thing happens for Ubuntu 22.04.

**Comment by beckerhe** [comment]
Hey Pierric,
how does the problem surfaces? Just no events or do you get an error message?
And do you have a log file?

Henning

**Comment by pierricgimmig** [comment]
When "DlopenInTracee" is called, I get:
463: [2022-10-26T15:48:39.743990] [UserSpaceInstrumentation/ExecuteMachineCode.cpp:88] Fatal: Failed to wait for sigtrap after PTRACE_CONT. Expected pid: 1776833 Pid returned from waitpid: 1776833 status: 2943, WIFSTOPPED: 1, WSTOPSIG: 11

I tried executing dummy code instead of the code that calls dlopen, simply executing an "int3" and resuming, and that works, so it doesn't look like it's a ptrace issue. 

It seems the injected code is making the target process crash.

To repro, run the tests on Ubuntu on 20.04 or 22.04 and see failures in ExecuteInProcessTest, InjectLibraryInTraceeTest and InstrumentProcessTest.

@danielfenner , any thoughts on what could be happening? 

Thanks!

**Comment by beckerhe** [comment]
That's interesting. The tests run fine for me in a Ubuntu 22.04 Docker container. 

Could this be some security/permission issue?

**Comment by pierricgimmig** [comment]
Thanks for checking. It might be a security/permission issue, I hope it is actually :-) Will continue investigating...

**Comment by pierricgimmig** [comment]
https://github.com/google/orbit/issues/4298 seems to be reporting the same issue.

**Comment by pierricgimmig** [comment]
The problem is that the memory allocated in the tracee is not readable on certain configurations it seems. There is a "EnsureMemoryExcecutable" that sets the permissions on the mapped memory to strictly "PROT_EXEC". This makes the tracee segfault when trying to read said memory. Setting the protection flag to "PROT_EXEC|PROT_READ" in the "EnsureMemoryExecutable" fixes the issue on my end and injection/orbit-dynamic-instrumentation/manual-instrumentation work.

**Comment by florian-kuebler** [comment]
Hey @pierricgimmig,

what you say sounds reasonable. I tried to reproduce the error on an Ubuntu 22.04 machine, and don't see it. So I can't test your proposed change. But it does not sound harmful. Would you be able to create a PR for that?

**Comment by pierricgimmig** [comment]
Fixed in https://github.com/google/orbit/pull/4328
