### ISSUE TITLE
Cpu usage percentages in start screen are off

### ISSUE THREAD

**Issue by danielfenner** [google/orbit#4333]
The cpu% column shows values that are a lot larger than plausible. This happens with different profiling targets. We superficially looked into the issue - this does not look like a recently introduced glitch but more like a real problem with the parsing and interpretation of the parsed values in src/ProcessService/ProcessServiceUtils.cpp.

**Comment by beckerhe** [comment]
We assume in the code that the number of jiffies of total cpu time spreads equally over all cores. This might not be true and result in too large percentage numbers. We need to have a look how tools like `top` (or other things from psutils) are doing that.
