### ISSUE TITLE
Connecting to OrbitService locally takes a long time

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#4404]
When profiling locally, if OrbitService is already running, connecting to it takes longer than before, a few seconds whereas it seemed instantaneous before the change that added the OrbitService launching button. @antonrohr , do you know why that is? The new feature is great btw, but it's unfortunate that it adds a bit of latency when firing up Orbit.

**Comment by antonrohr** [comment]
I am looking into this

**Comment by antonrohr** [comment]
I looked into this a bit and optimized how the gRPC connection is made in https://github.com/google/orbit/pull/4499

The bottomline is:
Orbit UI starts a gRPC channel to localhost on port 44765 and if OrbitService is already listening on 44765, the connection is very fast. So if you care about this speed, then I recommend starting OrbitService first (manually) and then start the Orbit UI. The `ConnectToLocalWidget` is written in a way that it can handle both, a manually started OrbitService and one started from the UI. 

If no one is listening on port 44765 then gRPC has a backoff algorithm that adds more and more delay between connection attempts. The PR mentioned above is setting up a new gRPC channel after the "Start OrbitService" button was clicked, so in theory that should mean the connection is also very fast. In practice there are small timing subtleties about what happens first, the listening or the connect on port 44765. 

I am going to close this, as in my testing it is fairly quick. Please reopen in case my suggestions do not work for you
