### ISSUE TITLE
error: static_assert failed due to requirement '0 == 1'

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#4482]
Fresh Ubuntu 22.04 build with latest code fails to compile, building clang12_relwithdebinfo.

```
/home/pierric/git/orbit/build_clang12_relwithdebinfo/src/OrbitVersion/OrbitVersion.cpp:19:1: error: static_assert failed due to requirement '0 == 1'
static_assert(OrbitMajorVersion == 1);
```

**Comment by florian-kuebler** [comment]
Hi @pierricgimmig, how did you cloned the repository?
This usually happens if the `git describe --always --match 1.*` fails/produces a wrong result.
You may have cloned a shallow copy of the repo (e.g. using `git cone --depth 1`), this way the check fails.

**Comment by pierricgimmig** [comment]
@florian-kuebler, I cloned the repo with `git clone https://github.com/google/orbit.git`

**Comment by florian-kuebler** [comment]
Very interesting.  You might want to check the output of `git describe --always --match 1.*`. But anyways. @beckerhe reverted the change that made this a static check. So you should be able to build again.
