### ISSUE TITLE
GraphTrack should not be templated

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#4534]
GraphTrack is templated based on the number of series it can hold. This is not ideal as we can't dynamically create a graph track that can hold an arbitrary number N of series, where N could only be determined at run time. It seems there is no benefit at all for templating this class. It adds complexity and can generate obscure compilation errors when using a base class method, for example:

```
declarations in dependent base ‘orbit_gl::CaptureViewElement’ are not found by unqualified lookup
../../../src/OrbitGl/LineGraphTrack.cpp:174:42: note: use ‘this->ClampToWorldExtentsX’ instead
```

**Comment by florian-kuebler** [comment]
+1. In particular this would help us to fix #4408, without implementing cgroup2 support (#4412), by simply removing the cgroup based information.
