### ISSUE TITLE
Orbit not compiling due to error in build 

### ISSUE THREAD

**Issue by fabianmpa** [google/orbit#4811]
I will put a screenshot rather than the complete log:
![image](https://user-images.githubusercontent.com/52846337/218144510-b12ee49e-da74-4a20-a52c-c699fbdb84ec.png)

It seems i am not selecting a target to build?

**Comment by fabianmpa** [comment]
Hi there. Sure, this is the output from the CMakeError log:

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/fabsmpa/orbit/build_default_release/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_fef23/fast && /usr/bin/make  -f CMakeFiles/cmTC_fef23.dir/build.make CMakeFiles/cmTC_fef23.dir/build
make[1]: Entering directory '/home/fabsmpa/orbit/build_default_release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_fef23.dir/src.c.o
/usr/bin/gcc-9 -DCMAKE_HAVE_LIBC_PTHREAD  -march=sandybridge -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -D_FORTIFY_SOURCE=2 -fstack-protector-all  -fPIE -o CMakeFiles/cmTC_fef23.dir/src.c.o -c /home/fabsmpa/orbit/build_default_release/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_fef23
/home/fabsmpa/.conan/data/cmake/3.24.1/_/_/package/5c09c752508b674ca5cb1f2d327b5a2d582866c8/bin/cmake -E cmake_link_script CMakeFiles/cmTC_fef23.dir/link.txt --verbose=1
/usr/bin/gcc-9 -march=sandybridge -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -D_FORTIFY_SOURCE=2 -fstack-protector-all  -Wl,-z,relro,-z,now,-z,noexecstack -pie  CMakeFiles/cmTC_fef23.dir/src.c.o -o cmTC_fef23 
/usr/bin/ld: CMakeFiles/cmTC_fef23.dir/src.c.o: in function `main':
src.c:(.text+0x6d): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x79): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x85): undefined reference to `pthread_cancel'
/usr/bin/ld: src.c:(.text+0x96): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_fef23.dir/build.make:99: cmTC_fef23] Error 1
make[1]: Leaving directory '/home/fabsmpa/orbit/build_default_release/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_fef23/fast] Error 2


Source file was:
#include <pthread.h>

static void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_cancel(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/fabsmpa/orbit/build_default_release/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_04acd/fast && /usr/bin/make  -f CMakeFiles/cmTC_04acd.dir/build.make CMakeFiles/cmTC_04acd.dir/build
make[1]: Entering directory '/home/fabsmpa/orbit/build_default_release/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_04acd.dir/CheckFunctionExists.c.o
/usr/bin/gcc-9   -march=sandybridge -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -D_FORTIFY_SOURCE=2 -fstack-protector-all -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE -o CMakeFiles/cmTC_04acd.dir/CheckFunctionExists.c.o -c /home/fabsmpa/.conan/data/cmake/3.24.1/_/_/package/5c09c752508b674ca5cb1f2d327b5a2d582866c8/share/cmake-3.24/Modules/CheckFunctionExists.c
Linking C executable cmTC_04acd
/home/fabsmpa/.conan/data/cmake/3.24.1/_/_/package/5c09c752508b674ca5cb1f2d327b5a2d582866c8/bin/cmake -E cmake_link_script CMakeFiles/cmTC_04acd.dir/link.txt --verbose=1
/usr/bin/gcc-9 -march=sandybridge -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -D_FORTIFY_SOURCE=2 -fstack-protector-all -DCHECK_FUNCTION_EXISTS=pthread_create -Wl,-z,relro,-z,now,-z,noexecstack -pie  CMakeFiles/cmTC_04acd.dir/CheckFunctionExists.c.o -o cmTC_04acd  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_04acd.dir/build.make:99: cmTC_04acd] Error 1
make[1]: Leaving directory '/home/fabsmpa/orbit/build_default_release/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_04acd/fast] Error 2

**Comment by florian-kuebler** [comment]
Sorry to be so late on this again. What system (including version) are you running on?
How did you triggered the build (bootstrap.sh, build.sh, cmake)?

**Comment by fabianmpa** [comment]
Do not worry, thanks for the support.

I am on Ubuntu 20.04.5 and triggered build with bootstrap.sh

**Comment by florian-kuebler** [comment]
I see. Unfortunately we only support Ubuntu 22 for now and don't really have resources right now to make 20 work.
I remember there were a couple of issues. Maybe @beckerhe has an idea on top of his head for the pthread issue?

**Comment by beckerhe** [comment]
Hi Fabian,
I don't think what you posted is the actual error message. This is just CMake testing on how to link against libpthread.

The full console output - as in your screenshot - would be helpful. It should shed some light on the problem.

**Comment by fabianmpa** [comment]
Hi there. I just got upgraded to Ubuntu 22 and still having the same output.

**Comment by florian-kuebler** [comment]
As @beckerhe mentioned, could you post the full output of the log, so that we can see the actual error message?

Running `bootstrap.sh` should be fine. What branch are you trying to build? `main`?

You could also try to build using system dependencies, as our CI does:
1. Install dependencies:
```
           sudo apt update &&                             \
           sudo apt install --yes --no-install-recommends \
           build-essential                                \
           clang-tidy-14                                  \
           cmake                                          \
           ccache                                         \
           libboost-dev                                   \
           libcapstone-dev                                \
           libgrpc++-dev                                  \
           libssh2-1-dev                                  \
           vulkan-validationlayers-dev                    \
           libz-dev                                       \
           llvm-dev                                       \
           protobuf-compiler-grpc                         \
           pkg-config                                     \
           libvulkan-volk-dev                             \
           libvulkan-dev                                  \
           libopengl-dev                                  \
           libglx-dev                                     \
           mesa-common-dev                                \
           qtbase5-dev                                    \
           libgtest-dev                                   \
           libgmock-dev                                   \
           git                                            \
           libprotobuf-dev
```
2. Build orbit:
```
mkdir build && cd build
cmake -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_CXX_FLAGS="-march=sandybridge -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer" \
  ..

cmake --build .
```

**Comment by fabianmpa** [comment]
Yes sure. I attached the log here:
[CMakeOutput.log](https://github.com/google/orbit/files/10937242/CMakeOutput.log)

Yes i am trying to build main branch.

With above cmake command i get this error:
[ 41%] Linking CXX executable ../../bin/LinuxTracingTests
/usr/bin/ld: CMakeFiles/LinuxTracingTests.dir/UprobesUnwindingVisitorMmapTest.cpp.o: in function `orbit_linux_tracing::UprobesUnwindingVisitorMmapTest_VisitMmapPerfEventUpdatesLibunwindstackMapsAndSendsModuleUpdates_Test::TestBody()':
UprobesUnwindingVisitorMmapTest.cpp:(.text+0x3bdb): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x3fbe): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x43b2): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x4c72): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x4f49): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: CMakeFiles/LinuxTracingTests.dir/UprobesUnwindingVisitorMmapTest.cpp.o: in function `orbit_linux_tracing::UprobesUnwindingVisitorMmapTest_VisitMmapPerfEventSendsModuleUpdatesForElfWithTextSplitAcrossTwoMaps_Test::TestBody()':
UprobesUnwindingVisitorMmapTest.cpp:(.text+0x5f36): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x6260): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x6b3c): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x73f9): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x76d2): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: CMakeFiles/LinuxTracingTests.dir/UprobesUnwindingVisitorMmapTest.cpp.o:UprobesUnwindingVisitorMmapTest.cpp:(.text+0x8dbf): more undefined references to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
/usr/bin/ld: CMakeFiles/LinuxTracingTests.dir/UprobesUnwindingVisitorMmapTest.cpp.o: in function `orbit_linux_tracing::UprobesUnwindingVisitorMmapTest_VisitMmapPerfEventSendsModuleUpdatesForPeTextSectionInAnonExecMap_Test::TestBody()':
UprobesUnwindingVisitorMmapTest.cpp:(.text+0x90d2): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: CMakeFiles/LinuxTracingTests.dir/UprobesUnwindingVisitorMmapTest.cpp.o: in function `orbit_linux_tracing::UprobesUnwindingVisitorMmapTest_VisitMmapPerfEventSendsModuleUpdatesForPeExecutableSectionsInBothFileAndAnonMaps_Test::TestBody()':
UprobesUnwindingVisitorMmapTest.cpp:(.text+0xa402): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xa721): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xafe4): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xb865): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xbb41): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: CMakeFiles/LinuxTracingTests.dir/UprobesUnwindingVisitorMmapTest.cpp.o: in function `orbit_linux_tracing::UprobesUnwindingVisitorMmapTest_VisitMmapPerfEventSendsModuleUpdatesForPeMappedByWine_Test::TestBody()':
UprobesUnwindingVisitorMmapTest.cpp:(.text+0xde89): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xe266): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xeb08): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xede6): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xf0ba): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xf38f): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xf665): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: CMakeFiles/LinuxTracingTests.dir/UprobesUnwindingVisitorMmapTest.cpp.o:UprobesUnwindingVisitorMmapTest.cpp:(.text+0xf93a): more undefined references to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)' follow
/usr/bin/ld: CMakeFiles/LinuxTracingTests.dir/UprobesUnwindingVisitorMmapTest.cpp.o: in function `orbit_linux_tracing::UprobesUnwindingVisitorMmapTest_VisitMmapPerfEventSendsModuleUpdatesForPeMappedByWine_Test::TestBody()':
UprobesUnwindingVisitorMmapTest.cpp:(.text+0xfc1f): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0xfef0): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x10790): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x10a66): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x10d3b): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
/usr/bin/ld: UprobesUnwindingVisitorMmapTest.cpp:(.text+0x11001): undefined reference to `testing::Matcher<std::basic_string_view<char, std::char_traits<char> > >::Matcher(char const*)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/LinuxTracing/CMakeFiles/LinuxTracingTests.dir/build.make:448: bin/LinuxTracingTests] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:6646: src/LinuxTracing/CMakeFiles/LinuxTracingTests.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2

At first i though it was compiler version error but realized that i have correct version of LLVM.

**Comment by alexkalmuk** [comment]
> At first i though it was compiler version error but realized that i have correct version of LLVM.

From your CMakeOutput.log:
```
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/g++-9 
```
I suspect gcc is used instead of clang compiler. Maybe you already have `g++-11` or `g++-12` installed in your 22.04, so you can use `update-alternatives` to set proper `/usr/bin/g++`.

**Comment by fabianmpa** [comment]
Hi, yes, now i can compile. Also what I needed to do was re built google test with C++17 standard because I had already built it with C++20 which was throwing the error with basic_string_view.
Thanks a lot for the support.
