### ISSUE TITLE
Add usage documentation for 1.0.2 (Windows)

### ISSUE THREAD

**Issue by EliteMasterEric** [google/orbit#4812]
Current documentation indicates that recent versions of Orbit are not functional on Windows. Development docs "recommend you to download the older 1.0.2 release from GitHub's releases page."

However, usage of this old version of the software is not straightforward, and any existing documentation or video guides have long been made private or deleted from the Internet entirely.

If this antiquated version of the program is being recommended to users, usage documentation (to the same standard as the current Linux version) should be made available.

**Comment by florian-kuebler** [comment]
Thanks for raising this.

The old Windows release is deprecated since quite some time, and we won't be able to add proper usage documentation for this version.

At least, I'll go forward and make this a bit more clear in our current documentation.
