### ISSUE TITLE
orbit: paly_lift.py   collison issue

### ISSUE THREAD

**Issue by tufeihenfei** [google/orbit#4835]
When I'm playing_ After importing our own robotic arm in the lift task, the gripper was unable to pick up the block due to the incorrect collision form. However, when I change the collision form of the gripper (from convex hull to other types, such as SDF, convex decomposition, mesh simplification, etc.), an error occurs:

2023 07 12 06:36:33 [55858ms] [Error] [omni. physx. plugin] PhysX error: PxArticulationLink: setCMassLocalPose(): it is illegal to call this method if PxSceneFlag: eSUPPRESS_ ARTICULATION_ READBACK is enabled!, FILE/buildAgent/work/16dcef52b68a730f/source/physx/src/NpArticulationLink.cpp, LINE 209
2023 07 12 06:36:33 [55859ms] [Error] [omni. physx. plugin] PhysX error: PxArticulationLink: setCMassLocalPose(): it is illegal to call this method if PxSceneFlag: eSUPPRESS_ ARTICULATION_ READBACK is enabled!, FILE/buildAgent/work/16dcef52b68a730f/source/physx/src/NpArticulationLink.cpp, LINE 209
![20230713-143722](https://github.com/google/orbit/assets/86908790/7f07661b-1f7a-477c-ae34-4cb21567ab3f)

May I ask how to solve this problem. thank you very much.

**Comment by florian-kuebler** [comment]
The issue seem to be about a different project.
