### ISSUE TITLE
Build is broken due to Orbit not having Conan lock files anymore

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#4844]
The build is very brittle as exposed [here](https://github.com/google/orbit/discussions/4667).

Now we have an issue that seems to be due to us abandoning lockfiles. It seems recipes were updated upstream with breaking changes and we can't build on Ubuntu 20.04 anymore, and I saw the same issue on Windows.

Any idea how to fix this, @beckerhe

**Comment by pierricgimmig** [comment]
See error [here](https://github.com/google/orbit/actions/runs/6244627574/job/16951847576)

```
zlib/1.3: Downloaded recipe revision 06023034579559bb64357db3a53f88a4
ERROR: Conflict in grpc/1.48.0:
    'grpc/1.48.0' requires 'zlib/1.2.13' while 'protobuf/3.21.4' requires 'zlib/1.3'.
    To fix this conflict you need to override the package 'zlib' in your root package.
ERROR: conanbuildinfo.txt file not found in D:\a\orbit\orbit\build
It is required for this command
You can generate it using 'conan install'
Error: Process completed with exit code 1.
```

**Comment by p3achyjr** [comment]
I'm currently seeing this on Ubuntu 20.04, even with the pending patch. Is there a workaround this atm?

**Comment by p3achyjr** [comment]
Weirdly enough--openssl, protobuf, and grpc all list zlib 1.2.13 as their version on the conan website.

**Comment by p3achyjr** [comment]
was able to workaround this by manually editing my ~/.conan cache to point to the correct dependencies.
