### ISSUE TITLE
Latest Conan version doesn't recognize llvm-core

### ISSUE THREAD

**Issue by Suhas44** [google/orbit#4876]
I updated to Conan 2.0 manually, and Orbit's build fails saying it doesn't recognize llvm-core. However, Conan's website still supports the package. The only way to fix this issue is to go back to 1.60, is there any way to make Orbit compatible with 2.x?

**Comment by Suhas44** [comment]
@beckerhe @pierricgimmig

**Comment by pierricgimmig** [comment]
Hi @Suhas44, see https://github.com/google/orbit/issues/4870, Conan 2 doesn't have LLVM support yet unfortunately

**Comment by Suhas44** [comment]
Got it, thank you.
