### ISSUE TITLE
Statistics view of instrumented functions in a capture

### ISSUE THREAD

**Issue by robbiesri** [google/orbit#56]
Would be cool to get some capture-wide statistics of instrumented functions.  The idea is that I might want to get a general idea of average characteristics of certain instrumented functions across an entire capture.

Possible statistics:
* Total count per instrumented function
* Average time per instrumented function
* Min/Max per instrumented function
* Std deviation per instrumented function

**Comment by pierricgimmig** [comment]
Some of those are already present in the "live" tab.  Will add the missing ones.

**Comment by robbiesri** [comment]
oh my god, how did I not notice this?? Very embarrassing.

I think that leaves just standard deviation! But that's really just a bonus, this is great!

**Comment by florian-kuebler** [comment]
Tracked internally under [b/184727547](b/184727547).

**Comment by florian-kuebler** [comment]
Fixed by: #2569
