### ISSUE TITLE
Refactor/Rename "Pdb" class for Linux.

### ISSUE THREAD

**Issue by pierricgimmig** [google/orbit#66]
There is a partial "Pdb" implementation on Linux that was temporarily put inside Module.cpp.  We need to rename the class ("DebugInfo"?) and properly separate the Linux and Windows implementations.

**Comment by beckerhe** [comment]
I believe @dpallotti is working on moving the whole PdB code intos its own module.

**Comment by dpallotti** [comment]
Not exactly, I'm looking into moving the Linux data collection to its own module but I might not touch that file. Maybe @dimitry- had an eye on this?

**Comment by dimitry-** [comment]
Yes, I am probably going to end up doing it at some point.

**Comment by florian-kuebler** [comment]
#1208 fixed this
