### ISSUE TITLE
Indicate Lost Events in the UI

### ISSUE THREAD

**Issue by florian-kuebler** [google/orbit#77]
There are situations, where certain events get lost, e.g. because of the buffer being to small or the traced function's execution time being to fast.
Here Orbit should resume working as expected, but notify the user (via. the UI), that she can't rely on the data being presented.

**Comment by dimitry-** [comment]
Tracking internally http://b/159106226

**Comment by florian-kuebler** [comment]
#2357, #2389 and #2494 fixed this.
