### ISSUE TITLE
Good to have  a tutorial page for new users

### ISSUE THREAD

**Issue by rerrabolu** [google/orbit#775]
The readme is not very clear.  I am wondering if there is a tutorial page on using orbit for linux systems. I am interested in getting a trace of the calls to a library of interest, including the ability to capture input  and return values.

**Comment by pierricgimmig** [comment]
Thanks for reminding us.  Better docs and tutorials are planned, but we should make them a higher priority.  What OS are you targeting by the way?

**Comment by rerrabolu** [comment]
I am using Ubuntu 18.04 LTS. I appreciate all the hard work that goes into
making something like this. One reason I believe software development
continues to be not very strong is because of lack of tools that are
simple, robust and stable. I often find it frustrating to see tools / etc
with poor documentation.

I think being able to log the various calls to shared libraries, their
statistics,  including serialization of input / output should be an
infrastructure service that is simply available to users. Lack of these is
what causes software development buggy and not robust.

Regards,
Ramesh

**Comment by pierricgimmig** [comment]
>I think being able to log the various calls to shared libraries, their statistics,  including serialization of input / output should be an infrastructure service that is simply available to users. Lack of these is what causes software development buggy and not robust.

I *totally* agree, this is exactly why Orbit was started.

> I am using Ubuntu 18.04 LTS.

On Linux, Orbit relies on uprobes and uretprobes to perform dynamic instrumentation.  We are using the perf_event_open api to enable the u(ret)probes.  Unfortunately, this a kernel feature that was introduced in the 4.17 kernel. To get Orbit working on Ubuntu, you'll have to either upgrade the kernel to 4.17 or upgrade Ubuntu to at least 19.04.  Once that's done, you'll have to build Orbit following the steps outlined [here](https://github.com/google/orbit/blob/master/DEVELOPMENT.md).  

To profile locally, you'll then have to start OrbitService as root locally and launch a UI instance:

```
sudo ./OrbitService
```

then 

```
./Orbit --local
```

**Comment by rerrabolu** [comment]
Recently, I had to upgrade my kernel version to something like 5.6. I will
look into it and see how it goes. Finally, if possible, it will be good if
orbit can be provided as a debian package.

Regards,
Ramesh

**Comment by pierricgimmig** [comment]
5.6 should be more than enough.  Concerning the Debian package, it will be available soon.

Thanks for your comments Ramesh, don't hesitate to reach out if you run into issues compiling Orbit.

Cheers, 

Pierric

**Comment by OAguinagalde** [comment]
I tried the latest release available and then realized it's rather old. I tried to install the master branch of the repo directly but I can't really manage to use. Reading the previous comments in this thread I discovered that I can run Orbit.exe -local to get inside the application but I can't figure out how to start the service. This is on windows, hope you can give me some steps on how to run the profiler locally, thanks!

**Comment by florian-kuebler** [comment]
> I tried the latest release available and then realized it's rather old. I tried to install the master branch of the repo directly but I can't really manage to use. Reading the previous comments in this thread I discovered that I can run Orbit.exe -local to get inside the application but I can't figure out how to start the service. This is on windows, hope you can give me some steps on how to run the profiler locally, thanks!

Hi Oscar. Unfortunately, windows local profiling is currently not supported with the current master version. For this you need to fallback to the 1.0.2. release.

**Comment by florian-kuebler** [comment]
#4272 is actually adding a comprehensive documentation. Closing this for now. Please re-open if there is anything missing.
