### ISSUE TITLE
Orbit spawns super many threads.

### ISSUE THREAD

**Issue by florian-kuebler** [google/orbit#87]
I noticed, that while capturing the current headless version(the service was the target) , Orbit constantly spawns new threads, that only do a short amount of work. Unfortunately, I did not had symbols available, so can not tell what work is done in these threads.

**Comment by pierricgimmig** [comment]
This comes for the LinuxUtils::ExecuteCommand function.  It's being used a lot... I'll see how we can achieve the same result with fewer thread spawning.
