### ISSUE TITLE
Difficult to read on HIDPI displays

### ISSUE THREAD

**Issue by PrototypeNM1** [google/orbit#94]
In the 1.0.2 release text is very difficult to read on HIDPI displays.

![image](https://user-images.githubusercontent.com/2732021/70786282-263f8c00-1d41-11ea-9bd5-82f4187ecf73.png)

**Comment by bartlomiejwolk** [comment]
I have a 4K display and the text is not visible at all.

**Comment by karupayun** [comment]
In newer versions, you can use scale the Capture Window using (Ctrl + and Ctrl -).
